# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: hernan
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLW11ZGR5LWR1c3QtYTUyZmNrdmsudXMtZWFzdC0yLmF3cy5uZW9uLnRlY2g6NTQzMi9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlCg== # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: N25leUJPMEZtcEp0  # en Base64
  API_BACKEND: aHR0cHM6Ly91cmJhbi1iYXNzb29uLXg1N3hxeHBweDZ4Mzk5cHItODA4NS5hcHAuZ2l0aHViLmRldi9jaWNsb1ZpZGE=
  #RAPIDAPI_KEY: ZWQ0ZGMyNjk3NG1zaDk0MmU1M2UzNGFhOTI2MXAxMzQxZmJqc24yOGUzODFhMTNlMzk= # en Base64
  #DATABASE_URL: ${DATABASE_URL}   # en Base64
  #DATABASE_USERNAME: ${DATABASE_USERNAME}   # en Base64
  #DATABASE_PASSWORD: ${DATABASE_PASSWORD}   # en Base64
  #API_KEY: ${API_KEY}   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode
